server:
  port: 80

spring:
  application:
    name: cloud-order-com.kealliang.springcloud.service

eureka:
  client:
    # 是否将自己注册进eureka 默认true
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka